backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artistes"
    label: "Artistes"
    folder: "_artistes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom de l'Artiste", name: "title", widget: "string" }
      - { label: "Domaine", name: "tag", widget: "string" }
      - { label: "Lien Photo Pinterest", name: "image_principale", widget: "string" }
      - { label: "Biographie", name: "body", widget: "text" }

