backend:
  name: github
  repo: ncaplace/NCSHARE
  branch: main

# Dossier d'enregistrement et chemin public
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artistes"
    label: "Artistes"
    folder: "_artistes"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Nom de l'artiste"
        name: "title"
        widget: "string"
        
      - label: "TAG"
        name: "tag"
        widget: "select"
        options:
          - "DESIGN"
          - "ART"
          - "MODE"
          - "ARCHITECTURE & SPACE"
          - "FOURNITURES"
      
      - label: "Image Principale"
        name: "image_principale"
        widget: "image"
      
      - label: "Biographie"
        name: "body"
        widget: "markdown"
