backend:
  name: github
  repo: ncaplace/NCSHARE
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artistes"
    label: "Artistes"
    folder: "_artistes"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Nom de l'artiste"
        name: "title"
        widget: "string"
        
      - label: "TAG"
        name: "tag"
        widget: "select"
        options:
          - "DESIGN"
          - "ART"
          - "MODE"
          - "ARCHITECTURE & SPACE"
          - "FOURNITURES"
      
      - label: "Image Principale"
        name: "image_principale"
        widget: "image"

      # --- CHOIX DU TYPE DE DESTINATION ---
      - label: "Activer un lien externe au clic (désactive la page individuelle)"
        name: "redirection_externe"
        widget: "boolean"
        default: false
        required: false

      - label: "Lien Externe (Ex: https://instagram.com/...)"
        name: "lien_externe"
        widget: "string"
        required: false

      - label: "Biographie (si la page individuelle est conservée)"
        name: "body"
        widget: "markdown"
        required: false
